service: lambda-aws-node10-sqs

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: sa-east-1
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:806197401294:logs"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${self:provider.region}:806197401294:*"

  environment:
    REGION: ${self:provider.region}
    QUEUE_NAME: logs

functions:
  sender:
    handler: sender.handler
    events:
      - http:
          path: sender/logs
          method: post
  receiver:
    handler: receiver.handler
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:806197401294:logs"
          batchSize: 1
    reservedConcurrency: 1

resources:
  Resources:
    logs:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: logs
